import { A } from '@solidjs/router'
import { JSX } from 'solid-js'
// @ts-expect-error Generated by pwa plugin
import { useRegisterSW } from 'virtual:pwa-register/solid'
import { db } from '../database/db'
import './Settings.css'

const Settings = (): JSX.Element => {
  const onDelete = (): void => {
    db.delete()
      .then(async () => await db.open())
      .catch(console.error)
  }

  const register = useRegisterSW()

  return (
    <main>
      <h1>Settings</h1>
      <div class="settings">
        <A class="button" href="/connection-types">
          Connection types
        </A>
        <button class="button" onClick={onDelete}>
          Delete data
        </button>
        <button class="button" onClick={() => register?.updateServiceWorker()}>
          Update
        </button>
      </div>
    </main>
  )
}

export default Settings
